sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t nvidmar/docker-react .

script:
  - docker run -e CI=true nvidmar/docker-react npm run test