FROM node:alpine

WORKDIR /usr/app

COPY package.json .

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install

COPY . .

RUN chown -R node:node /usr/app/node_modules

CMD ["npm", "run", "start"]